### ISSUE TITLE
Allow users to remove shortened URLs

### ISSUE THREAD

**Issue by mikybars** [mperezi/aws-lambda-url-shortener#10]
## Problem

Currently there is no way of editing or removing shortened URLs so that they point to a different place. Therefore users that create URLs with meaningful names (aka _custom paths_, e.g. [migueli.to/dotfiles](https://migueli.to/dotfiles)) are stuck with their initial choice till the end of times. 

## Concerns

In order to support the _remove_ feature we actually require the notion of _users_ first so that a given user can not remove shortened URLs created by others. In addition, provided we implement users we might as well restrict custom paths only to logged in users to prevent "URL hoarding attacks".

## Tasks

- [ ] Implement user management via [Cognito](https://aws.amazon.com/es/cognito/).
- [ ] Map the Cognito configuration to the Serverless framework format.
- [ ] Implement a new Lambda function to list all the shortened URLs created by a user.
- [ ] Implement "My list of URLs" in the UI.
- [ ] Implement a new Lambda function to remove a URL.
- [ ] Modify the UI to include a remove button next to each URL.
